Impl timeout to suspend
rogy-AquaLab/2024_cavolinia_nucleo pull request #13
Opened 2024-08-19 02:31 UTC by H1rono

close #11

2024-08-19 06:24 UTC, Chikurin1014 requested changes

2024-08-19 06:24 UTC, Chikurin1014 commented on src/main.cpp
>          }
ここに入ることは基本的にないとは思うのですが、一応`output.suspend()`を入れておいてもらえますか?

2024-08-19 06:25 UTC, Chikurin1014 commented on src/main.cpp
>          }
```cpp
if (read < 1) {
    output.suspend();
    continue;
}
```

2024-08-19 06:37 UTC, Chikurin1014 commented on src/main.cpp
> -            trigger_setup.wait_any(1, osWaitForever, false);
5秒はちょっと長いかも。
基本的にPCとの接続が切れたら動かないでほしいのと、`SUSPEND`からの復帰はそこまで難しくないことを考えれば、長くてもせいぜい1秒くらいで良いと思います。

2024-08-19 06:39 UTC, Chikurin1014 requested changes

2024-08-19 06:39 UTC, Chikurin1014 commented on src/main.cpp
> +            const uint32_t res = flags.wait_any_for(WATCH_FLAGS, 5s);
5秒はちょっと長いかも

基本的に接続がないときに動かないでほしいことと、一度`SUSPEND`になっても復帰はできるのことを考慮すると、長くても1秒くらいかなと思いました。

2024-08-19 07:32 UTC, H1rono commented on src/main.cpp
>          }
`TRIGGER_SUSPEND`フラグ作る

2024-08-19 08:37 UTC, Chikurin1014 approved these changes
`INITIALIZING` -> `SUSPEND`の状態遷移が発生しなくなった気がする。
`RUNNING`に入った直後に`SUSPEND`に遷移させれば良いので、個人的にはそこまで悪いことだとは思わないですが。

Issueで言及していた内容から逸れてくるけど、ここまで来ると`OutputMachine`に組み込めそう。あるいは`OutputMachineAsync`とかにしてまとめられそう。

2024-08-19 08:40 UTC, H1rono commented
動作確認できたらマージする

2024-08-19 09:01 UTC, H1rono commented
落ちた

```
++ MbedOS Fault Handler ++

FaultType: HardFault

Context:
R   0: 20000A94
R   1: FFFFFFFF
R   2: 20000A94
R   3: 00000001
R   4: 20000A94
R   5: 20000AB4
R   6: FFFFFFFF
R   7: 20000AB0
R   8: 20000E6C
R   9: 00000000
R  10: 00000000
R  11: 00000000
R  12: 08001039
SP   : 20002FA8
LR   : 08000259
PC   : 0800107E
xPSR : 2100000B
PSP  : 20000AD0
MSP  : 20002F88
CPUID: 410FC241
HFSR : 40000000
MMFSR: 00000000
BFSR : 00000004
UFSR : 00000000
DFSR : 00000008
AFSR : 00000000
Mode : Handler
Priv : Privileged
Stack: MSP

-- MbedOS Fault Handler --



++ MbedOS Error Info ++
Error Status: 0x80FF013D Code: 317 Module: 255
Error Message: Fault exception
Location: 0x800107E
Error Value: 0x20001B20
Current Thread: main <handler> Id: 0x20000AB4 Entry: 0x800A1AC StackSize: 0x800133E StackMem: 0x8001333 SP: 0x20002FA8
For more info, visit: https://mbed.com/s/error?error=0x80FF013D&tgt=NUCLEO_F303K8
-- MbedOS Error Info --
```

2024-08-19 09:21 UTC, H1rono commented
https://os.mbed.com/docs/mbed-os/v6.16/debug-test/analyzing-mbed-os-crash-dump.html

2024-08-19 15:28 UTC, H1rono commented
https://github.com/ARMmbed/mbed-os-example-fault-handler 使ってみた

```
Crash Info:
        Crash location = <unknown-symbol> [0x0800107E] (based on PC value)
        Caller location = <unknown-symbol> [0x08000259] (based on LR value)
        Stack Pointer at the time of crash = [20002FA8]
        Target and Fault Info:
                Processor Arch: ARM-V7M or above
                Processor Variant: C24
                Forced exception, a fault with configurable priority has been escalated to HardFault
                Imprecise data access error has occurred
```

2024-08-20 06:56 UTC, Chikurin1014 requested changes

2024-08-20 06:56 UTC, Chikurin1014 commented on src/main.cpp
> +            const uint32_t res = flags.wait_any_for(TRIGGER_INITIALIZE_FLAG, 1s, false);
`initialize`については1秒おきにタイムアウトせずにずっと待ち続けていても良さそうに思いました。

何か理由があったらすみません。

2024-08-20 06:56 UTC, Chikurin1014 commented on src/main.cpp
> +            if (res & RECEIVED_INPUT_FLAG) {
実装上存在しないですが、`res == RECEIVED_INPUT_FLAG | TRIGGER_SUSPEND_FLAG`の場合が正しくハンドリングされていないのが気になります。(サスペンドしてほしい)

例えば以下のような書き方ではダメでしょうか?
```cpp
const bool failed_to_recieve_input = (res & RECIEVED_INPUT) == 0;
const bool trigger_suspend_flag = (res & TRIGGER_SUSPEND_FLAG) != 0;
if (failed_to_recieve_input || trigger_suspend_flag) {
    output.suspend();
}
```

2024-08-20 07:55 UTC, H1rono commented on src/main.cpp
> +            const uint32_t res = flags.wait_any_for(TRIGGER_INITIALIZE_FLAG, 1s, false);
特に理由はない
`wait_any`を避けようと思っただけ

2024-08-20 09:36 UTC, H1rono commented
```
++ MbedOS Error Info ++
Error Status: 0x80010137 Code: 311 Module: 1
Error Message: EventFlags: 0x200007A4, Parameter error
Location: 0x80022CF
Error Value: 0x200007A4
Current Thread: application_unnamed_thread Id: 0x20000B4C Entry: 0x80076ED StackSize: 0x1F8 StackMem: 0x20001010 SP: 0x20002F3C
For more info, visit: https://mbed.com/s/error?error=0x80010137&tgt=NUCLEO_F303K8
-- MbedOS Error Info --
```

2024-08-20 19:55 UTC, H1rono commented
なんと、動く

2024-08-20 22:07 UTC, Chikurin1014 requested changes

2024-08-20 22:07 UTC, Chikurin1014 commented on src/umiusi/outputs.cpp
> +/// ESC の起動待ち
もう消しちゃっていいかも

2024-08-20 22:07 UTC, Chikurin1014 commented on src/main.cpp
> +    std::atomic_bool     received_input;
センサ類の`inputs`と被ってるので`order`とかに変えたいです

2024-08-20 22:18 UTC, Chikurin1014 approved these changes

2024-08-21 00:54 UTC, merged